// Generated by CoffeeScript 1.7.1
(function() {
  var body, config;

  config = exports;

  config.state = "open";

  config.hoursAgo = 1;

  body = "User details:\n\n";

  body += "Plan: {plan_name}\n\n";

  body += "Account: https://transloadit.com/admin/accounts/{account_email}";

  config.formData = {
    authorName: "Tim Koschützki",
    authorEmail: "tim.koschuetzki@transloadit.com",
    body: body,
    internal: true,
    skip_spam: true
  };

  config.tender = {
    siteName: process.env.TENDER_SITENAME,
    apiKey: process.env.TENDER_APIKEY,
    project: process.env.TENDER_PROJECT
  };

}).call(this);
